###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    # nginx reverse-proxy
    webserver:
        container_name: vuesample-webserver
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '60004:80'
        depends_on:
            - php-fpm
            - vue-frontend

    # php backend
    php-fpm:
        container_name: vuesample-backend
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
        ports:
            - '9000:9000'

    # vue frontend with vite
    vue-frontend:
        container_name: vuesample-frontend
        image: node:18-alpine
        working_dir: /application
        volumes:
            - './vueapp_vite:/application'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        command: sh -c "npm install && npm run dev -- --host"
